name: Django test

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test action
        run: echo "hello world"
